"""Turning a beam into preference pairs.

`reports/phase3/nbest.md` closed the reranking question and left this one open.
The beam contains a correction much better than the one the model ranks first --
oracle 0.8380 against top-1 0.7148 on held-out dev, replicated on the screen --
and no selector built from features *outside* the model reaches it. Sequence
score, edit distance, beam consensus and a nine-feature logistic regression all
land within 0.001 of top-1, because what separates `der meisten Firmen` from
`den meisten Firmen` is German case agreement and none of those features can
read German.

Preference training is not bounded that way. It changes the parameters rather
than the ranking, so it can learn the agreement instead of a proxy for it. The
pairs are free: the model generated both sides itself, and the gold annotation
says which one is better, so nothing here is distilled from a larger model --
which is why cLang-8 was declined and this was not.

**Both sides are whole answers.** The beam stops at the `changes` marker, because
the correction is the only field scored and generating the rest would cost width
for nothing. The pair cannot stop there. TRL appends an EOS token to both
completions with no way to switch it off, so a pair carrying a truncated answer
teaches the model to end one -- `{"correction": ..., "changes":` followed by a
full stop, and the schema breaks on every sentence rather than the 1 in 2,903 it
breaks on now.

So the `changes` list is rebuilt from the candidate, by the ERRANT pass that
derives the learner-facing explanation anyway, and each side ends where an answer
really ends. The first draft of this module truncated instead, on the argument
that iteration 4 had shown the `changes` list to be 70% of the tokens and worth
down-weighting in the SFT loss. That argument is about where gradient is spent
and it does not reach this: a DPO completion is not a target to imitate, it is
one half of a comparison, and the comparison has to be between two things the
model could actually emit.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from typing import Any

from langlm.eval import errant_de
from langlm.eval import m2_scorer as m2
from langlm.train.format import build_target


@dataclass(frozen=True)
class Pair:
    """One preference pair, both sides generated by the model being trained."""

    #: The sentence the model was asked to correct, as the prompt it saw.
    prompt: str
    #: The answer scoring best against the annotator.
    chosen: str
    #: The answer the model ranked first, which is what it would have served.
    rejected: str
    #: Position of the chosen candidate in the beam. Never 0.
    chosen_rank: int
    #: How much better the chosen side is, in true positives minus false ones.
    gain: int


def distance(a: Sequence[str], b: Sequence[str]) -> int:
    """Token-level Levenshtein distance."""
    previous = list(range(len(b) + 1))
    for i, left in enumerate(a, start=1):
        current = [i]
        for j, right in enumerate(b, start=1):
            current.append(
                previous[j - 1]
                if left == right
                else 1 + min(previous[j - 1], previous[j], current[j - 1])
            )
        previous = current
    return previous[-1]


def complete_answer(source: str, correction: str) -> str:
    """One candidate as a whole answer in the training schema.

    The beam gives a correction and stops. This puts the `changes` list back,
    derived from the candidate by the same German ERRANT that derives the
    explanation at serving time, so the completion ends where an answer ends --
    see the module docstring for why a truncated one cannot be used.

    Args:
        source: The learner sentence, whitespace-tokenised.
        correction: The candidate correction, whitespace-tokenised.

    Returns:
        The JSON answer, identical in shape to what SFT was trained on.
    """
    edits = errant_de.annotate(source, correction)
    return build_target(
        {
            "source": source,
            "target": correction,
            "edits": [
                {
                    "start": edit.start,
                    "end": edit.end,
                    "correction": edit.correction,
                    "error_type": edit.error_type,
                }
                for edit in edits
            ],
        }
    )


def _key(source: list[str], candidate: dict[str, Any], gold) -> tuple[int, int]:
    """How good a candidate is, and how narrow -- the oracle's ordering.

    The same ordering `scripts/nbest_rerank.py` measures the oracle with, so the
    pairs are drawn from exactly the gap that report quantified. Ties go to the
    narrower edit, which keeps the preferred side from teaching the model to
    reach further than it has to.
    """
    hypothesis = candidate["text"].split()
    counts = m2.sentence_counts(source, hypothesis, gold)
    return counts.tp - counts.fp, -distance(source, hypothesis)


def build_pairs(
    sentences,
    records: list[list[dict[str, Any]]],
    prompts: list[str],
    answer_for=complete_answer,
) -> list[Pair]:
    """Pair the beam's best candidate against the one the model ranked first.

    A pair is emitted only where the model is *wrong about its own beam*: the
    best candidate is not the top-ranked one, and it is strictly better rather
    than merely narrower. Ties produce nothing to learn from -- preferring the
    narrower of two equally correct answers is a decoding preference, not German.

    Args:
        sentences: The `M2Sentence` records the beams were generated from.
        records: Per sentence, the beam as ``{'answer', 'text', 'score'}``, in
            the model's own ranking with the top-ranked candidate first.
        prompts: Per sentence, the prompt the model was given.
        answer_for: How a candidate becomes a completion, as
            ``(source, correction) -> str``. Injectable so the pairing logic can
            be tested without loading a parser.

    Returns:
        One `Pair` per sentence that has something to teach, in input order.
    """
    pairs: list[Pair] = []
    for sentence, record, prompt in zip(sentences, records, prompts, strict=True):
        if len(record) < 2:
            continue
        source, gold = sentence.source_tokens, sentence.edits_for()

        keys = [_key(source, candidate, gold) for candidate in record]
        best = max(range(len(record)), key=lambda index: keys[index])
        if best == 0 or keys[best][0] <= keys[0][0]:
            continue
        # Identical text can be reached by two beams with different scores. The
        # pair would be a no-op in the loss and a divide-by-zero in the margin.
        if record[best]["text"] == record[0]["text"]:
            continue

        pairs.append(
            Pair(
                prompt=prompt,
                chosen=answer_for(sentence.source, record[best]["text"]),
                rejected=answer_for(sentence.source, record[0]["text"]),
                chosen_rank=best,
                gain=keys[best][0] - keys[0][0],
            )
        )
    return pairs
