#!/usr/bin/env python
"""Is the oracle candidate predictable without the gold?

`scripts/nbest_rerank.py` establishes two facts on held-out dev: the beam
contains a much better correction than the one the model ranks first (oracle
0.8380 against beam top-1 0.7148), and neither of the cheap unsupervised
selectors reaches it -- the minimum-edit prior is worth +0.0007 over beam top-1
and MBR is worth less than nothing.

That leaves one question before anything expensive is built. Those selectors are
single hand-set statistics. Is the oracle candidate separable from its siblings
by *any* feature combination, or is the gap only reachable with the answer in
hand? A learned reranker is the cheap way to ask, and it is also the screen on
whether preference training is worth a generation pass over Falko train.

    python scripts/rerank_features.py --train-size 2000

Trains on n-best over Falko-MERLIN *train*, where the gold says which candidate
was best, and reports on the cached held-out dev n-best -- sentences neither the
features nor the penalty were fitted on. The test split is not touched.
"""

from __future__ import annotations

import argparse
import difflib
import json
from types import SimpleNamespace

import numpy as np

from langlm.config import INTERIM_DIR, load_config
from langlm.data.splits import load_split
from langlm.eval import m2_scorer as m2
from langlm.eval import subset
from nbest_rerank import CACHE_DIR, distance, generate, rerank

#: Order matters only for reading the printed weights.
FEATURES = [
    "score",
    "score_margin",
    "rank",
    "edits",
    "edits_per_token",
    "length_delta",
    "diff_ops",
    "mbr_risk",
    "identical_siblings",
]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--adapter", default="checkpoints/phase3-de-iter4-cw025")
    parser.add_argument("--train-size", type=int, default=2000)
    parser.add_argument("--beams", type=int, default=5)
    parser.add_argument("--batch-size", type=int, default=4)
    parser.add_argument("--max-new-tokens", type=int, default=384)
    parser.add_argument("--penalty", type=float, default=0.02)
    parser.add_argument("--epochs", type=int, default=400)
    parser.add_argument("--regenerate", action="store_true")
    args = parser.parse_args()

    phase1, phase3 = load_config("phase1"), load_config("phase3")
    beta = phase1["evaluation"]["beta"]

    train = load_split("falko_merlin", "train")[: args.train_size]
    print(f"train: {len(train):,} sentences, {args.beams} beams")
    train_records = generate(
        SimpleNamespace(
            adapter=args.adapter,
            name=f"train{args.train_size}",
            beams=args.beams,
            batch_size=args.batch_size,
            max_new_tokens=args.max_new_tokens,
            regenerate=args.regenerate,
        ),
        train,
        phase3,
    )

    x_train, y_train = dataset(
        train_records, [s.source_tokens for s in train], [s.edits_for() for s in train]
    )
    print(f"  {len(x_train):,} candidates, {int(y_train.sum()):,} of them oracle-best")

    mean, std = x_train.mean(axis=0), x_train.std(axis=0)
    std[std == 0] = 1.0
    weights = fit((x_train - mean) / std, y_train, epochs=args.epochs)
    print("\n--- what it learned (standardised weights) ---")
    for name, weight in sorted(zip(FEATURES, weights[:-1], strict=True), key=lambda p: -abs(p[1])):
        print(f"  {name:20s} {weight:+.3f}")

    # Held-out dev: generated by the previous script, never fitted on.
    dev = load_split("falko_merlin", phase1["evaluation"]["split"])
    _, chosen = subset.take(dev)
    held_out = set(chosen)
    positions = [i for i in range(len(dev)) if i not in held_out]
    sentences = [dev[i] for i in positions]

    path = CACHE_DIR / f"iter4-cw025-heldout.beams{args.beams}.{len(sentences)}.jsonl"
    if not path.exists():
        raise SystemExit(f"No cached held-out n-best at {path}. Run nbest_rerank.py --complement.")
    records = [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines()]
    sources = [s.source_tokens for s in sentences]

    print(f"\n--- held-out dev: {len(sentences):,} sentences ---")
    rows = []
    greedy = greedy_lines(positions)
    if greedy:
        rows.append(("greedy (published path)", *scored(sentences, greedy, beta)))
    rows.append(("beam top-1", *scored(sentences, [r[0]["text"] for r in records], beta)))
    picked = [rerank(r, s, args.penalty) for r, s in zip(records, sources, strict=True)]
    rows.append((f"min-edit, penalty {args.penalty:g}", *scored(sentences, picked, beta)))

    picked = []
    moved = 0
    for record, source in zip(records, sources, strict=True):
        features = (candidate_features(record, source) - mean) / std
        best = int(np.argmax(features @ weights[:-1] + weights[-1]))
        moved += best != 0
        picked.append(record[best]["text"])
    rows.append(("learned reranker", *scored(sentences, picked, beta)))

    picked, _ = oracle_pick(records, sources, [s.edits_for() for s in sentences])
    rows.append(("oracle (per-sentence best)", *scored(sentences, picked, beta)))

    print(f"{'selection':30s} {'F0.5':>7s} {'P':>7s} {'R':>7s}")
    for label, f, p, r in rows:
        print(f"{label:30s} {f:7.4f} {p:7.4f} {r:7.4f}")
    print(f"\nlearned reranker moves off top-1 on {moved:,} of {len(records):,} sentences")


def candidate_features(record: list[dict], source: list[str]) -> np.ndarray:
    """Features for every candidate of one sentence. No gold is consulted."""
    texts = [c["text"].split() for c in record]
    scores = [c["score"] for c in record]
    top = max(scores)
    rows = []
    for index, (candidate, score) in enumerate(zip(texts, scores, strict=True)):
        edits = distance(source, candidate)
        ops = sum(
            1
            for tag, *_ in difflib.SequenceMatcher(a=source, b=candidate).get_opcodes()
            if tag != "equal"
        )
        risk = sum(distance(candidate, other) for other in texts) / max(len(texts) - 1, 1)
        identical = sum(1 for other in texts if other == candidate) - 1
        rows.append(
            [
                score,
                score - top,
                float(index),
                float(edits),
                edits / max(len(source), 1),
                float(len(candidate) - len(source)),
                float(ops),
                risk,
                float(identical),
            ]
        )
    return np.array(rows, dtype=np.float64)


def dataset(records, sources, golds) -> tuple[np.ndarray, np.ndarray]:
    """Features and an is-oracle-best label for every candidate."""
    x, y = [], []
    for record, source, gold in zip(records, sources, golds, strict=True):
        features = candidate_features(record, source)
        keys = []
        for candidate in record:
            counts = m2.sentence_counts(source, candidate["text"].split(), gold)
            keys.append((counts.tp - counts.fp, -distance(source, candidate["text"].split())))
        best = max(range(len(record)), key=lambda i: keys[i])
        for index in range(len(record)):
            x.append(features[index])
            y.append(1.0 if index == best else 0.0)
    return np.array(x), np.array(y)


def fit(x: np.ndarray, y: np.ndarray, epochs: int, lr: float = 0.5) -> np.ndarray:
    """Logistic regression by gradient descent. No sklearn in the environment."""
    weights = np.zeros(x.shape[1] + 1)
    design = np.hstack([x, np.ones((len(x), 1))])
    for _ in range(epochs):
        predicted = 1.0 / (1.0 + np.exp(-design @ weights))
        weights -= lr * (design.T @ (predicted - y)) / len(y)
    return weights


def oracle_pick(records, sources, golds):
    picked, changed = [], 0
    for record, source, gold in zip(records, sources, golds, strict=True):
        keys = []
        for candidate in record:
            counts = m2.sentence_counts(source, candidate["text"].split(), gold)
            keys.append((counts.tp - counts.fp, -distance(source, candidate["text"].split())))
        best = max(range(len(record)), key=lambda i: keys[i])
        picked.append(record[best]["text"])
        changed += best != 0
    return picked, changed


def greedy_lines(positions) -> list[str] | None:
    path = INTERIM_DIR / "phase3" / "iter4-cw025.dev.2503.txt"
    if not path.exists():
        return None
    lines = path.read_text(encoding="utf-8").splitlines()
    return [lines[i] for i in positions]


def scored(sentences, hypotheses, beta: float):
    result = m2.score(sentences, hypotheses, beta=beta)
    return result.f_score, result.precision, result.recall


if __name__ == "__main__":
    main()
